import type { PrintingCategoryId } from './printing'

export type PrintingProduct = {
  id: string
  slug: string
  category: PrintingCategoryId
  name: string
  summary: string
  image: string
  imageAlt: string
  startingPrice: number
  currency: 'SAR'
  sizes: string[]
  materials: string[]
  isActive: boolean
}

/**
 * MVP printing catalog. Frontend configuration only — no PrintingProduct
 * table, no admin CRUD, and no quantity/material pricing in Task 11.
 * Task 12 can look up products by `slug`.
 */
export const PRINTING_PRODUCTS: PrintingProduct[] = [
  {
    id: 'bc-standard',
    slug: 'standard-business-cards',
    category: 'business-cards',
    name: 'كروت شخصية قياسية',
    summary: 'كروت تعريف يومية بلمسة نظيفة تناسب الاستخدام اليومي.',
    image: '/printing/business-cards.svg',
    imageAlt: 'نموذج كروت شخصية قياسية',
    startingPrice: 85,
    currency: 'SAR',
    sizes: ['قياس قياسي', 'مخصص'],
    materials: ['ورق مطفي', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'bc-premium',
    slug: 'premium-business-cards',
    category: 'business-cards',
    name: 'كروت شخصية فاخرة',
    summary: 'خامة أثقل ولمسة أنعم لحضور أقوى في اللقاءات.',
    image: '/printing/business-cards-premium.svg',
    imageAlt: 'نموذج كروت شخصية فاخرة',
    startingPrice: 180,
    currency: 'SAR',
    sizes: ['قياس قياسي', 'مخصص'],
    materials: ['كرتون', 'ورق مطفي'],
    isActive: true,
  },
  {
    id: 'bc-luxury',
    slug: 'luxury-business-cards',
    category: 'business-cards',
    name: 'كروت شخصية فاخرة مطلية',
    summary: 'تشطيب فاخر للكروت التي تمثّل الهوية في المناسبات الخاصة.',
    image: '/printing/business-cards-luxury.svg',
    imageAlt: 'نموذج كروت شخصية فاخرة مطلية',
    startingPrice: 320,
    currency: 'SAR',
    sizes: ['قياس قياسي', 'مخصص'],
    materials: ['كرتون', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'flyers-a5',
    slug: 'a5-flyers',
    category: 'flyers',
    name: 'فلايرز A5',
    summary: 'منشورات بحجم عملي للتوزيع في الفعاليات ونقاط البيع.',
    image: '/printing/flyers.svg',
    imageAlt: 'نموذج فلايرز مقاس A5',
    startingPrice: 120,
    currency: 'SAR',
    sizes: ['A5', 'مخصص'],
    materials: ['ورق مطفي', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'flyers-a4',
    slug: 'a4-flyers',
    category: 'flyers',
    name: 'فلايرز A4',
    summary: 'مساحة أوضح للعروض التفصيلية والقوائم.',
    image: '/printing/flyers-a4.svg',
    imageAlt: 'نموذج فلايرز مقاس A4',
    startingPrice: 180,
    currency: 'SAR',
    sizes: ['A4', 'A5'],
    materials: ['ورق مطفي', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'flyers-premium',
    slug: 'premium-flyers',
    category: 'flyers',
    name: 'فلايرز فاخرة',
    summary: 'طباعة أثقل للعروض التي تحتاج حضوراً بصرياً أعلى.',
    image: '/printing/flyers-premium.svg',
    imageAlt: 'نموذج فلايرز فاخرة',
    startingPrice: 280,
    currency: 'SAR',
    sizes: ['A5', 'A4', 'مخصص'],
    materials: ['كرتون', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'stickers-diecut',
    slug: 'die-cut-stickers',
    category: 'stickers',
    name: 'استيكرات قص خاص',
    summary: 'قص يتبع شكل الشعار أو المنتج بدقة.',
    image: '/printing/stickers.svg',
    imageAlt: 'نموذج استيكرات بقص خاص',
    startingPrice: 90,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط', 'مخصص'],
    materials: ['فينيل', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'stickers-round',
    slug: 'round-stickers',
    category: 'stickers',
    name: 'استيكرات دائرية',
    summary: 'ملصقات دائرية للختم، التغليف، والهدايا.',
    image: '/printing/stickers-round.svg',
    imageAlt: 'نموذج استيكرات دائرية',
    startingPrice: 70,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط'],
    materials: ['فينيل', 'ورق مطفي'],
    isActive: true,
  },
  {
    id: 'stickers-labels',
    slug: 'product-labels',
    category: 'stickers',
    name: 'ليبل منتجات',
    summary: 'ملصقات تعريف للمنتجات والعبوات.',
    image: '/printing/stickers-labels.svg',
    imageAlt: 'نموذج ليبل منتجات',
    startingPrice: 110,
    currency: 'SAR',
    sizes: ['قياسي', 'مخصص'],
    materials: ['فينيل', 'ورق لامع', 'كرافت'],
    isActive: true,
  },
  {
    id: 'boxes-folding',
    slug: 'folding-boxes',
    category: 'boxes',
    name: 'علب قابلة للطي',
    summary: 'علب خفيفة للشحن والعرض السريع.',
    image: '/printing/boxes.svg',
    imageAlt: 'نموذج علب قابلة للطي',
    startingPrice: 250,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط', 'مخصص'],
    materials: ['كرتون', 'كرافت'],
    isActive: true,
  },
  {
    id: 'boxes-product',
    slug: 'product-boxes',
    category: 'boxes',
    name: 'علب منتجات',
    summary: 'علب حماية وعرض للمنتج النهائي.',
    image: '/printing/boxes-product.svg',
    imageAlt: 'نموذج علب منتجات',
    startingPrice: 320,
    currency: 'SAR',
    sizes: ['متوسط', 'كبير', 'مخصص'],
    materials: ['كرتون', 'ورق مطفي'],
    isActive: true,
  },
  {
    id: 'boxes-gift',
    slug: 'gift-boxes',
    category: 'boxes',
    name: 'علب هدايا',
    summary: 'علب تقديم بهوية العلامة للمناسبات.',
    image: '/printing/boxes-gift.svg',
    imageAlt: 'نموذج علب هدايا',
    startingPrice: 400,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط', 'مخصص'],
    materials: ['كرتون', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'bags-paper',
    slug: 'paper-bags',
    category: 'bags',
    name: 'أكياس ورقية',
    summary: 'أكياس عملية للتسوق والتسليم اليومي.',
    image: '/printing/bags.svg',
    imageAlt: 'نموذج أكياس ورقية',
    startingPrice: 150,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط', 'كبير'],
    materials: ['كرافت', 'ورق مطفي'],
    isActive: true,
  },
  {
    id: 'bags-luxury',
    slug: 'luxury-shopping-bags',
    category: 'bags',
    name: 'أكياس تسوق فاخرة',
    summary: 'مقبض متين وطباعة أوضح لتجربة استلام أرقى.',
    image: '/printing/bags-luxury.svg',
    imageAlt: 'نموذج أكياس تسوق فاخرة',
    startingPrice: 280,
    currency: 'SAR',
    sizes: ['متوسط', 'كبير'],
    materials: ['كرتون', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'bags-custom',
    slug: 'custom-printed-bags',
    category: 'bags',
    name: 'أكياس مطبوعة مخصصة',
    summary: 'طباعة كاملة للشعار والألوان حسب الهوية.',
    image: '/printing/bags-custom.svg',
    imageAlt: 'نموذج أكياس مطبوعة مخصصة',
    startingPrice: 220,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط', 'مخصص'],
    materials: ['كرافت', 'ورق مطفي', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'pack-product',
    slug: 'product-packaging',
    category: 'packaging',
    name: 'تغليف منتجات',
    summary: 'تغليف يحمي المنتج ويظهره بشكل مرتب.',
    image: '/printing/packaging.svg',
    imageAlt: 'نموذج تغليف منتجات',
    startingPrice: 350,
    currency: 'SAR',
    sizes: ['قياسي', 'مخصص'],
    materials: ['كرتون', 'كرافت'],
    isActive: true,
  },
  {
    id: 'pack-food',
    slug: 'food-packaging',
    category: 'packaging',
    name: 'تغليف غذائي',
    summary: 'حلول تغليف مناسبة لعرض المنتجات الغذائية.',
    image: '/printing/packaging-food.svg',
    imageAlt: 'نموذج تغليف غذائي',
    startingPrice: 380,
    currency: 'SAR',
    sizes: ['صغير', 'متوسط', 'مخصص'],
    materials: ['كرتون', 'ورق مطفي'],
    isActive: true,
  },
  {
    id: 'pack-branded',
    slug: 'branded-packaging',
    category: 'packaging',
    name: 'تغليف بهوية العلامة',
    summary: 'تغليف مطبوع بالكامل ليحمل ألوان وشعار العلامة.',
    image: '/printing/packaging-branded.svg',
    imageAlt: 'نموذج تغليف بهوية العلامة',
    startingPrice: 450,
    currency: 'SAR',
    sizes: ['قياسي', 'مخصص'],
    materials: ['كرتون', 'ورق لامع', 'كرافت'],
    isActive: true,
  },
  {
    id: 'posters-a3',
    slug: 'a3-posters',
    category: 'posters',
    name: 'بوسترات A3',
    summary: 'بوسترات داخلية واضحة للنقاط البيعية والمكاتب.',
    image: '/printing/posters.svg',
    imageAlt: 'نموذج بوسترات مقاس A3',
    startingPrice: 90,
    currency: 'SAR',
    sizes: ['A3', 'A4'],
    materials: ['ورق مطفي', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'posters-a2',
    slug: 'a2-posters',
    category: 'posters',
    name: 'بوسترات A2',
    summary: 'حجم أكبر للواجهات الداخلية والمعارض.',
    image: '/printing/posters-a2.svg',
    imageAlt: 'نموذج بوسترات مقاس A2',
    startingPrice: 140,
    currency: 'SAR',
    sizes: ['A2', 'A3'],
    materials: ['ورق مطفي', 'ورق لامع'],
    isActive: true,
  },
  {
    id: 'posters-large',
    slug: 'large-format-posters',
    category: 'posters',
    name: 'بوسترات مقاس كبير',
    summary: 'طباعة عريضة للفعالية والواجهات.',
    image: '/printing/posters-large.svg',
    imageAlt: 'نموذج بوسترات مقاس كبير',
    startingPrice: 280,
    currency: 'SAR',
    sizes: ['A2', 'كبير', 'مخصص'],
    materials: ['ورق لامع', 'فينيل'],
    isActive: true,
  },
  {
    id: 'custom-printed',
    slug: 'custom-printed-product',
    category: 'custom-products',
    name: 'منتج مطبوع حسب الطلب',
    summary: 'تنفيذ حر عندما لا تكفي القوالب الجاهزة.',
    image: '/printing/custom.svg',
    imageAlt: 'نموذج منتج مطبوع حسب الطلب',
    startingPrice: 500,
    currency: 'SAR',
    sizes: ['مخصص'],
    materials: ['ورق مطفي', 'كرتون', 'فينيل', 'كرافت'],
    isActive: true,
  },
  {
    id: 'custom-promo',
    slug: 'custom-promotional-product',
    category: 'custom-products',
    name: 'منتج دعائي مخصص',
    summary: 'مواد دعائية بتصميم وتنفيذ وفق احتياج الحملة.',
    image: '/printing/custom-promo.svg',
    imageAlt: 'نموذج منتج دعائي مخصص',
    startingPrice: 450,
    currency: 'SAR',
    sizes: ['قياسي', 'مخصص'],
    materials: ['ورق لامع', 'كرتون', 'فينيل'],
    isActive: true,
  },
]

export function getPrintingProducts(category?: PrintingCategoryId | null): PrintingProduct[] {
  const active = PRINTING_PRODUCTS.filter((product) => product.isActive)

  if (!category) {
    return active
  }

  return active.filter((product) => product.category === category)
}

export function getPrintingProductBySlug(slug: string): PrintingProduct | undefined {
  return PRINTING_PRODUCTS.find((product) => product.slug === slug && product.isActive)
}

export function printingCustomizePath(slug: string): string {
  return `/printing/customize/${encodeURIComponent(slug)}`
}
